In [1]:
import pandas as pd 
import numpy as np
from pathlib import Path

In [2]:
def load_csv(folder_path):
    datasets = {}

    for file in Path(folder_path).glob("*.csv"):

        df = pd.read_csv(file)

        df.columns = (
            df.columns
            .str.strip()
            .str.lower()
            .str.replace(" ", "_")
        )

        print(f"\n{file.name}")
        print(df.isnull().sum())

        datasets[file.stem] = df

    return datasets

In [3]:
data = load_csv(r"C:\Users\RUCHIR\anaconda_projects\New_project")

customers.csv
customer_id           0
customer_name        15
email               118
phone                 0
city                  0
state                 0
signup_date          75
customer_segment      0
dtype: int64

orders.csv
order_id          0
customer_id       0
order_date      191
warehouse_id      0
order_status      0
payment_mode      0
dtype: int64

order_items.csv
order_item_id     0
order_id          0
product_id        0
quantity         40
discount_pct      0
dtype: int64

products.csv
product_id      0
product_name    0
category        0
sub_category    0
unit_price      7
weight_kg       0
supplier_id     0
dtype: int64

shipments.csv
shipment_id          0
order_id             0
ship_date          196
delivery_date      181
carrier              0
shipping_cost      169
delivery_status      0
dtype: int64

suppliers.csv
supplier_id          0
supplier_name        0
country              0
lead_time_days       0
reliability_score    2
dtype: int64

warehouses.csv
warehouse_id      0
warehouse_name    0
city              0
state             0
capacity_units    0
dtype: int64

In [4]:
orders = data["orders"]
customers = data["customers"]
products = data["products"]
order_items = data["order_items"]
products = data["products"]
shipments = data["shipments"]
suppliers = data["suppliers"]
warehouses = data["warehouses"]

In [5]:
orders["order_date"] = (pd.to_datetime(orders["order_date"], format = "mixed", errors = "coerce", dayfirst=True).dt.strftime("%Y-%m-%d"))
orders["order_date"] = pd.to_datetime(orders["order_date"], format = "mixed", errors = "coerce", dayfirst=True)

In [6]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9030 entries, 0 to 9029
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   order_id      9030 non-null   object
 1   customer_id   9030 non-null   object
 2   order_date    8687 non-null   datetime64[ns]
 3   warehouse_id  9030 non-null   object
 4   order_status  9030 non-null   object
 5   payment_mode  9030 non-null   object
dtypes: datetime64[ns](1), object(5)
memory usage: 423.4+ KB

In [7]:
shipments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9050 entries, 0 to 9049
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   shipment_id      9050 non-null   object
 1   order_id         9050 non-null   object
 2   ship_date        8854 non-null   object
 3   delivery_date    8869 non-null   object
 4   carrier          9050 non-null   object
 5   shipping_cost    8881 non-null   float64
 6   delivery_status  9050 non-null   object
dtypes: float64(1), object(6)
memory usage: 495.1+ KB

In [8]:
shipments["ship_date"] = (pd.to_datetime(shipments["ship_date"], format = "mixed", errors = "coerce", dayfirst=True).dt.strftime("%Y-%m-%d"))
shipments["ship_date"] = pd.to_datetime(shipments["ship_date"], format = "mixed", errors = "coerce", dayfirst=True)

shipments["delivery_date"] = (pd.to_datetime(shipments["delivery_date"], format = "mixed", errors = "coerce", dayfirst=True).dt.strftime("%Y-%m-%d"))
shipments["delivery_date"] = pd.to_datetime(shipments["delivery_date"], format = "mixed", errors = "coerce", dayfirst=True)

In [9]:
shipments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9050 entries, 0 to 9049
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   shipment_id      9050 non-null   object
 1   order_id         9050 non-null   object
 2   ship_date        8729 non-null   datetime64[ns]
 3   delivery_date    8739 non-null   datetime64[ns]
 4   carrier          9050 non-null   object
 5   shipping_cost    8881 non-null   float64
 6   delivery_status  9050 non-null   object
dtypes: datetime64[ns](2), float64(1), object(4)
memory usage: 495.1+ KB

In [10]:
def parse_messy_date(series):
    formats = ["%Y-%m-%d", "%d-%m-%Y", "%d/%m/%Y", "%m/%d/%Y", "%d %b %Y", "%Y/%m/%d"]
    result = pd.Series(pd.NaT, index=series.index)
    remaining = series.astype(str).str.strip()
    for fmt in formats:
        parsed = pd.to_datetime(remaining, format=fmt, errors="coerce")
        result = result.fillna(parsed)
        remaining = remaining.where(parsed.isna())
    return result
shipments["ship_date"] = parse_messy_date(shipments["ship_date"])
shipments["delivery_date"] = parse_messy_date(shipments["delivery_date"])

In [11]:
shipments[["delivery_date", "ship_date"]]

     delivery_date  ship_date
0       2024-07-08 2024-04-07
1       2022-09-06 2022-09-05
2       2024-04-19 2024-04-04
3       2024-11-30 2024-11-29
4       2023-07-10 2023-07-04
...            ...        ...
9045    2022-04-05 2022-04-01
9046    2024-02-20 2024-02-13
9047    2022-07-03 2022-06-30
9048    2024-06-08 2024-01-06
9049    2024-03-01 2023-12-26

[9050 rows x 2 columns]

In [12]:
customers["signup_date"] = (pd.to_datetime(customers["signup_date"], format = "mixed", errors = "coerce", dayfirst=True).dt.strftime("%Y-%m-%d"))
customers["signup_date"] = pd.to_datetime(customers["signup_date"], format = "mixed", errors = "coerce", dayfirst=True)

In [13]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4025 entries, 0 to 4024
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       4025 non-null   object
 1   customer_name     4010 non-null   object
 2   email             3907 non-null   object
 3   phone             4025 non-null   int64
 4   city              4025 non-null   object
 5   state             4025 non-null   object
 6   signup_date       3891 non-null   datetime64[ns]
 7   customer_segment  4025 non-null   object
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 251.7+ KB

### checking for nulls

In [14]:
order_items.isnull().sum()

order_item_id     0
order_id          0
product_id        0
quantity         40
discount_pct      0
dtype: int64

In [15]:
order_items[ "quantity"].isnull().any()

np.True_

In [16]:
order_items = order_items.dropna(subset=["quantity"])

In [17]:
order_items[ "quantity"].isnull().any()

np.False_

### Dropped All the Null values of Quantity

In [18]:
orders[orders["order_date"].isnull()]

,order_id,customer_id,order_date,warehouse_id,order_status,payment_mode
44,ORD000045,CUST03263,NaT,WH004,Processing,COD
82,ORD000083,CUST03763,NaT,WH015,Delivered,UPI
117,ORD000118,CUST02421,NaT,WH017,Cancelled,UPI
120,ORD000121,CUST00894,NaT,WH011,pending,COD
136,ORD000137,CUST02079,NaT,WH017,Shipped,Debit Card
...,...,...,...,...,...,...
8983,ORD008984,CUST01108,NaT,WH013,Pending,Cash on Delivery
8986,ORD008987,CUST00714,NaT,WH012,Cancelled,cod
8995,ORD008996,CUST02930,NaT,WH009,Cancelled,UPI
8998,ORD008999,CUST02635,NaT,WH012,Shipped,cod
9003,ORD003421,CUST03201,NaT,WH002,Shipped,UPI

In [19]:
orders = orders.dropna(subset=["order_date"])

In [20]:
orders.isnull().sum()

order_id        0
customer_id     0
order_date      0
warehouse_id    0
order_status    0
payment_mode    0
dtype: int64

In [21]:
products.isnull().sum()

product_id      0
product_name    0
category        0
sub_category    0
unit_price      7
weight_kg       0
supplier_id     0
dtype: int64

In [22]:
products[products["unit_price"].isnull()].reset_index()

,index,product_id,product_name,category,sub_category,unit_price,weight_kg,supplier_id
0,56,PROD00057,Team Sports Item 57,Sports,team sports,NaN,7.23,SUP0020
1,86,PROD00087,Snacks Item 87,Grocery,Snacks,NaN,16.80,SUP0026
2,196,PROD00197,Outdoor Item 197,SPORTS,Outdoor,NaN,15.06,SUP0002
3,286,PROD00287,Fitness Item 287,Sports,fitness,NaN,19.35,SUP0012
4,416,PROD00417,Fiction Item 417,Books,fiction,NaN,9.60,SUP0030
5,448,PROD00449,WATCHES ITEM 449,fashion,Watches,NaN,1.75,SUP0044
6,469,PROD00470,Fitness Item 470,Sports,FITNESS,NaN,16.06,SUP0041

In [23]:
products = products.dropna(subset=["unit_price"])

In [24]:
products.isnull().sum()

product_id      0
product_name    0
category        0
sub_category    0
unit_price      0
weight_kg       0
supplier_id     0
dtype: int64

In [25]:
shipments.isnull().sum()

shipment_id          0
order_id             0
ship_date          321
delivery_date      311
carrier              0
shipping_cost      169
delivery_status      0
dtype: int64

In [26]:
shipments[shipments["ship_date"].isnull() & 
    shipments["delivery_date"].isnull()
    ].reset_index()

,index,shipment_id,order_id,ship_date,delivery_date,carrier,shipping_cost,delivery_status
0,471,SHP000472,ORD000472,NaT,NaT,IndiaPost,328.71,Lost
1,667,SHP000668,ORD000668,NaT,NaT,Delhivery,637.87,Lost
2,2040,SHP002041,ORD002041,NaT,NaT,XPRESSBEES,729.59,DELAYED
3,2109,SHP002110,ORD002110,NaT,NaT,Delhivery,373.08,in transit
4,2650,SHP002651,ORD002651,NaT,NaT,IndiaPost,623.23,In Transit
5,3969,SHP003970,ORD003970,NaT,NaT,DTDC,40.08,LOST
6,4407,SHP004408,ORD004408,NaT,NaT,Ekart,821.67,In Transit
7,5119,SHP005120,ORD005120,NaT,NaT,Delhivery,46.76,Returned to Origin
8,6217,SHP006218,ORD006218,NaT,NaT,fedex,101.85,Delivered
9,6279,SHP006280,ORD006280,NaT,NaT,fedex,860.67,returned to origin
10,7800,SHP007801,ORD007801,NaT,NaT,Ekart,88.53,Lost
11,8204,SHP008205,ORD008205,NaT,NaT,DTDC,54.76,Delayed

In [27]:
shipments = shipments.drop(
    shipments[shipments["ship_date"].isnull() & 
    shipments["delivery_date"].isnull()
    ].index)

In [28]:
shipments.isnull().sum()

shipment_id          0
order_id             0
ship_date          309
delivery_date      299
carrier              0
shipping_cost      169
delivery_status      0
dtype: int64

In [29]:
suppliers.isnull().sum()

supplier_id          0
supplier_name        0
country              0
lead_time_days       0
reliability_score    2
dtype: int64

In [30]:
suppliers[suppliers["reliability_score"].isnull()]

   supplier_id   supplier_name    country  lead_time_days  reliability_score
1      SUP0002  garcia traders  Indonesia               3                NaN
21     SUP0022   Davis Traders    Germany              21                NaN

In [31]:
products.info()

<class 'pandas.core.frame.DataFrame'>
Index: 601 entries, 0 to 607
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    601 non-null    object
 1   product_name  601 non-null    object
 2   category      601 non-null    object
 3   sub_category  601 non-null    object
 4   unit_price    601 non-null    object
 5   weight_kg     601 non-null    float64
 6   supplier_id   601 non-null    object
dtypes: float64(1), object(6)
memory usage: 37.6+ KB

In [32]:
products["unit_price"] = pd.to_numeric(products["unit_price"], errors="coerce")

C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\468104651.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products["unit_price"] = pd.to_numeric(products["unit_price"], errors="coerce")

In [33]:
products.info()

<class 'pandas.core.frame.DataFrame'>
Index: 601 entries, 0 to 607
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    601 non-null    object
 1   product_name  601 non-null    object
 2   category      601 non-null    object
 3   sub_category  601 non-null    object
 4   unit_price    571 non-null    float64
 5   weight_kg     601 non-null    float64
 6   supplier_id   601 non-null    object
dtypes: float64(2), object(5)
memory usage: 37.6+ KB

In [34]:
products[products["unit_price"]<0]

,product_id,product_name,category,sub_category,unit_price,weight_kg,supplier_id
21,PROD00022,Storage Item 22,HOME & KITCHEN,STORAGE,-14487.64,12.32,SUP0037
51,PROD00052,Furniture Item 52,HOME & KITCHEN,Furniture,-4090.71,11.23,SUP0024
120,PROD00121,non-fiction item 121,books,NON-FICTION,-1875.64,23.35,SUP0003
299,PROD00300,Academic Item 300,BOOKS,Academic,-1411.72,20.35,SUP0031
376,PROD00377,STAPLES ITEM 377,Grocery,Staples,-775.43,22.53,SUP0042
452,PROD00453,Cameras Item 453,Electronics,Cameras,-16171.76,14.78,SUP0009
537,PROD00538,Men Clothing Item 538,Fashion,Men Clothing,-3173.92,0.88,SUP0021

In [35]:
products.drop(products[products["unit_price"]<0].index, inplace=True)

C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\2514240210.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  products.drop(products[products["unit_price"]<0].index, inplace=True)

In [36]:
products[products["unit_price"]<0]

Empty DataFrame
Columns: [product_id, product_name, category, sub_category, unit_price, weight_kg, supplier_id]
Index: []

In [37]:
products

,product_id,product_name,category,sub_category,unit_price,weight_kg,supplier_id
0,PROD00001,Team Sports Item 1,Sports,Team Sports,6735.55,13.88,SUP0013
1,PROD00002,Bags Item 2,fashion,Bags,2149.16,8.09,SUP0029
2,PROD00003,non-fiction item 3,BOOKS,non-fiction,1908.75,7.79,SUP0052
3,PROD00004,Dairy Item 4,Grocery,Dairy,952.05,6.14,SUP0042
4,PROD00005,Cameras Item 5,Electronics,Cameras,13521.05,3.38,SUP0030
...,...,...,...,...,...,...,...
603,PROD00312,Comics Item 312,BOOKS,COMICS,691.31,24.95,SUP0030
604,PROD00177,BAGS ITEM 177,FASHION,Bags,3014.90,23.84,SUP0016
605,PROD00135,Cookware Item 135,Home & Kitchen,cookware,9305.31,0.35,SUP0034
606,PROD00552,Women Clothing Item 552,FASHION,WOMEN CLOTHING,2369.98,21.07,SUP0017
607,PROD00153,Mobiles Item 153,Electronics,Mobiles,49963.41,2.49,SUP0047

### Making a delivery day column and removing unrealistic delivery dates

In [38]:
shipments["delivery_days"] = (shipments["delivery_date"] - shipments["ship_date"]).dt.days
print(shipments["delivery_days"].describe())
print((shipments["delivery_days"] < 0).sum())

count    8430.000000
mean        5.385884
std        51.218837
min      -323.000000
25%         3.000000
50%         5.000000
75%         8.000000
max       332.000000
Name: delivery_days, dtype: float64
502

In [39]:
# Drop all rows with impossible delivery_days (negative or unrealistically large)
shipments_clean = shipments[
    (shipments["delivery_days"] >= 0) & (shipments["delivery_days"] <= 20)
].copy()

print(f"Original rows: {len(shipments)}")
print(f"Dropped rows: {len(shipments) - len(shipments_clean)}")
print(f"Remaining rows: {len(shipments_clean)}")

# sanity check
print(shipments_clean["delivery_days"].describe())

# use this going forward
shipments = shipments_clean

Original rows: 9038
Dropped rows: 1594
Remaining rows: 7444
count    7444.000000
mean        5.822676
std         3.850071
min         1.000000
25%         3.000000
50%         5.000000
75%         8.000000
max        15.000000
Name: delivery_days, dtype: float64

In [40]:
shipments.head()

,shipment_id,order_id,ship_date,delivery_date,carrier,shipping_cost,delivery_status,delivery_days
1,SHP000002,ORD000002,2022-09-05,2022-09-06,IndiaPost,413.53,delivered,1.0
2,SHP000003,ORD000003,2024-04-04,2024-04-19,DTDC,552.47,Delivered,15.0
3,SHP000004,ORD000004,2024-11-29,2024-11-30,DTDC,66.02,Delivered,1.0
4,SHP000005,ORD000005,2023-07-04,2023-07-10,DTDC,82.97,Returned to Origin,6.0
5,SHP000006,ORD000006,2023-04-09,2023-04-11,BlueDart,801.61,In Transit,2.0

In [41]:
shipments["delivery_days"]

1        1.0
2       15.0
3        1.0
4        6.0
5        2.0
        ...
9040     5.0
9041     4.0
9045     4.0
9046     7.0
9047     3.0
Name: delivery_days, Length: 7444, dtype: float64

In [42]:
warehouses.isnull().sum()

warehouse_id      0
warehouse_name    0
city              0
state             0
capacity_units    0
dtype: int64

### Checking for duplicates

In [43]:
orders.duplicated().sum()

np.int64(29)

In [44]:
order_items.duplicated().sum()

np.int64(0)

In [45]:
products.duplicated().sum()

np.int64(8)

In [46]:
customers.duplicated().sum()

np.int64(25)

In [47]:
warehouses.duplicated().sum()

np.int64(0)

In [48]:
shipments.duplicated().sum()

np.int64(15)

In [49]:
suppliers.duplicated().sum()

np.int64(3)

In [50]:
orders[orders.duplicated()]

,order_id,customer_id,order_date,warehouse_id,order_status,payment_mode
9000,ORD003844,CUST00419,2024-03-13,WH016,Processing,Net Banking
9001,ORD006189,CUST00118,2024-11-25,WH016,PENDING,COD
9002,ORD003491,CUST01023,2023-12-19,WH016,Shipped,Debit Card
9004,ORD005290,CUST01461,2022-05-15,WH005,Delivered,cod
9005,ORD003737,CUST02869,2022-09-13,WH018,Delivered,Net Banking
9006,ORD004086,CUST02386,2023-12-29,WH008,Processing,UPI
9007,ORD001044,CUST01636,2022-07-30,WH012,Cancelled,UPI
9008,ORD004362,CUST00741,2024-01-14,WH013,Processing,COD
9009,ORD007343,CUST01918,2023-08-06,WH006,Delivered,COD
9010,ORD007528,CUST02753,2022-10-01,WH013,Pending,COD
9011,ORD003530,CUST00520,2022-06-20,WH015,Pending,Net Banking
9012,ORD004270,CUST00471,2024-11-15,WH006,Pending,COD
9013,ORD005785,CUST02106,2024-05-25,WH018,Cancelled,Debit Card
9014,ORD001158,CUST01432,2023-04-23,WH012,SHIPPED,Debit Card
9015,ORD005862,CUST01940,2023-04-24,WH009,Processing,COD
9016,ORD008683,CUST03952,2023-02-03,WH006,processing,cod
9017,ORD000251,CUST02226,2024-03-07,WH015,Pending,Net Banking
9018,ORD003127,CUST03342,2024-05-31,WH014,Returned,Credit Card
9019,ORD004295,CUST02562,2024-01-18,WH008,Processing,Debit Card
9020,ORD003673,CUST01777,2024-03-27,WH010,shipped,Cash on Delivery
9021,ORD004811,CUST00326,2023-10-22,WH013,Shipped,cod
9022,ORD007266,CUST02327,2022-07-28,WH006,Delivered,UPI
9023,ORD005873,CUST03037,2023-10-23,WH005,Pending,Credit Card
9024,ORD007974,CUST01874,2023-05-11,WH004,Cancelled,UPI
9025,ORD005867,CUST03689,2023-01-14,WH009,Processing,Cash on Delivery
9026,ORD007733,CUST01489,2022-03-17,WH008,Pending,Net Banking
9027,ORD007123,CUST00344,2024-08-18,WH015,Cancelled,UPI
9028,ORD000043,CUST01526,2023-08-08,WH010,Delivered,cod
9029,ORD008941,CUST01102,2022-07-19,WH007,Delivered,Net Banking

In [51]:
orders[orders.duplicated(keep=False)].sort_values("order_id")

,order_id,customer_id,order_date,warehouse_id,order_status,payment_mode
42,ORD000043,CUST01526,2023-08-08,WH010,Delivered,cod
9028,ORD000043,CUST01526,2023-08-08,WH010,Delivered,cod
250,ORD000251,CUST02226,2024-03-07,WH015,Pending,Net Banking
9017,ORD000251,CUST02226,2024-03-07,WH015,Pending,Net Banking
1043,ORD001044,CUST01636,2022-07-30,WH012,Cancelled,UPI
9007,ORD001044,CUST01636,2022-07-30,WH012,Cancelled,UPI
1157,ORD001158,CUST01432,2023-04-23,WH012,SHIPPED,Debit Card
9014,ORD001158,CUST01432,2023-04-23,WH012,SHIPPED,Debit Card
3126,ORD003127,CUST03342,2024-05-31,WH014,Returned,Credit Card
9018,ORD003127,CUST03342,2024-05-31,WH014,Returned,Credit Card
9002,ORD003491,CUST01023,2023-12-19,WH016,Shipped,Debit Card
3490,ORD003491,CUST01023,2023-12-19,WH016,Shipped,Debit Card
3529,ORD003530,CUST00520,2022-06-20,WH015,Pending,Net Banking
9011,ORD003530,CUST00520,2022-06-20,WH015,Pending,Net Banking
3672,ORD003673,CUST01777,2024-03-27,WH010,shipped,Cash on Delivery
9020,ORD003673,CUST01777,2024-03-27,WH010,shipped,Cash on Delivery
3736,ORD003737,CUST02869,2022-09-13,WH018,Delivered,Net Banking
9005,ORD003737,CUST02869,2022-09-13,WH018,Delivered,Net Banking
9000,ORD003844,CUST00419,2024-03-13,WH016,Processing,Net Banking
3843,ORD003844,CUST00419,2024-03-13,WH016,Processing,Net Banking
9006,ORD004086,CUST02386,2023-12-29,WH008,Processing,UPI
4085,ORD004086,CUST02386,2023-12-29,WH008,Processing,UPI
4269,ORD004270,CUST00471,2024-11-15,WH006,Pending,COD
9012,ORD004270,CUST00471,2024-11-15,WH006,Pending,COD
9019,ORD004295,CUST02562,2024-01-18,WH008,Processing,Debit Card
4294,ORD004295,CUST02562,2024-01-18,WH008,Processing,Debit Card
9008,ORD004362,CUST00741,2024-01-14,WH013,Processing,COD
4361,ORD004362,CUST00741,2024-01-14,WH013,Processing,COD
9021,ORD004811,CUST00326,2023-10-22,WH013,Shipped,cod
4810,ORD004811,CUST00326,2023-10-22,WH013,Shipped,cod
9004,ORD005290,CUST01461,2022-05-15,WH005,Delivered,cod
5289,ORD005290,CUST01461,2022-05-15,WH005,Delivered,cod
9013,ORD005785,CUST02106,2024-05-25,WH018,Cancelled,Debit Card
5784,ORD005785,CUST02106,2024-05-25,WH018,Cancelled,Debit Card
9015,ORD005862,CUST01940,2023-04-24,WH009,Processing,COD
5861,ORD005862,CUST01940,2023-04-24,WH009,Processing,COD
9025,ORD005867,CUST03689,2023-01-14,WH009,Processing,Cash on Delivery
5866,ORD005867,CUST03689,2023-01-14,WH009,Processing,Cash on Delivery
9023,ORD005873,CUST03037,2023-10-23,WH005,Pending,Credit Card
5872,ORD005873,CUST03037,2023-10-23,WH005,Pending,Credit Card
9001,ORD006189,CUST00118,2024-11-25,WH016,PENDING,COD
6188,ORD006189,CUST00118,2024-11-25,WH016,PENDING,COD
9027,ORD007123,CUST00344,2024-08-18,WH015,Cancelled,UPI
7122,ORD007123,CUST00344,2024-08-18,WH015,Cancelled,UPI
9022,ORD007266,CUST02327,2022-07-28,WH006,Delivered,UPI
7265,ORD007266,CUST02327,2022-07-28,WH006,Delivered,UPI
9009,ORD007343,CUST01918,2023-08-06,WH006,Delivered,COD
7342,ORD007343,CUST01918,2023-08-06,WH006,Delivered,COD
7527,ORD007528,CUST02753,2022-10-01,WH013,Pending,COD
9010,ORD007528,CUST02753,2022-10-01,WH013,Pending,COD
9026,ORD007733,CUST01489,2022-03-17,WH008,Pending,Net Banking
7732,ORD007733,CUST01489,2022-03-17,WH008,Pending,Net Banking
7973,ORD007974,CUST01874,2023-05-11,WH004,Cancelled,UPI
9024,ORD007974,CUST01874,2023-05-11,WH004,Cancelled,UPI
9016,ORD008683,CUST03952,2023-02-03,WH006,processing,cod
8682,ORD008683,CUST03952,2023-02-03,WH006,processing,cod
8940,ORD008941,CUST01102,2022-07-19,WH007,Delivered,Net Banking
9029,ORD008941,CUST01102,2022-07-19,WH007,Delivered,Net Banking

In [52]:
orders = orders.drop_duplicates()

In [53]:
orders.duplicated().sum()

np.int64(0)

In [54]:
shipments[shipments.duplicated(keep=False) ].sort_values("order_id")

,shipment_id,order_id,ship_date,delivery_date,carrier,shipping_cost,delivery_status,delivery_days
830,SHP000831,ORD000831,2024-11-23,2024-11-27,BlueDart,41.75,Returned to Origin,4.0
9041,SHP000831,ORD000831,2024-11-23,2024-11-27,BlueDart,41.75,Returned to Origin,4.0
2193,SHP002194,ORD002194,2022-10-13,2022-10-18,IndiaPost,173.16,LOST,5.0
9040,SHP002194,ORD002194,2022-10-13,2022-10-18,IndiaPost,173.16,LOST,5.0
2270,SHP002271,ORD002271,2022-04-01,2022-04-05,Delhivery,778.27,Returned to Origin,4.0
9045,SHP002271,ORD002271,2022-04-01,2022-04-05,Delhivery,778.27,Returned to Origin,4.0
2610,SHP002611,ORD002611,2022-09-14,2022-09-21,DELHIVERY,285.14,Delayed,7.0
9039,SHP002611,ORD002611,2022-09-14,2022-09-21,DELHIVERY,285.14,Delayed,7.0
3775,SHP003776,ORD003776,2022-07-30,2022-08-05,Delhivery,432.43,delayed,6.0
9033,SHP003776,ORD003776,2022-07-30,2022-08-05,Delhivery,432.43,delayed,6.0
3787,SHP003788,ORD003788,2022-07-21,2022-07-23,BlueDart,332.13,In Transit,2.0
9035,SHP003788,ORD003788,2022-07-21,2022-07-23,BlueDart,332.13,In Transit,2.0
9047,SHP004122,ORD004122,2022-06-30,2022-07-03,dtdc,747.96,delayed,3.0
4121,SHP004122,ORD004122,2022-06-30,2022-07-03,dtdc,747.96,delayed,3.0
9034,SHP004201,ORD004201,2022-07-02,2022-07-12,FedEx,263.42,Lost,10.0
4200,SHP004201,ORD004201,2022-07-02,2022-07-12,FedEx,263.42,Lost,10.0
9030,SHP004502,ORD004502,2022-07-30,2022-08-14,Delhivery,535.16,In Transit,15.0
4501,SHP004502,ORD004502,2022-07-30,2022-08-14,Delhivery,535.16,In Transit,15.0
9046,SHP004989,ORD004989,2024-02-13,2024-02-20,FedEx,880.66,Delayed,7.0
4988,SHP004989,ORD004989,2024-02-13,2024-02-20,FedEx,880.66,Delayed,7.0
9032,SHP005740,ORD005740,2022-04-30,2022-05-07,XPRESSBEES,769.11,Delayed,7.0
5739,SHP005740,ORD005740,2022-04-30,2022-05-07,XPRESSBEES,769.11,Delayed,7.0
9036,SHP005885,ORD005885,2022-06-27,2022-06-30,Ekart,474.72,lost,3.0
5884,SHP005885,ORD005885,2022-06-27,2022-06-30,Ekart,474.72,lost,3.0
9031,SHP006926,ORD006926,2022-10-17,2022-10-22,XPRESSBEES,125.67,Delivered,5.0
6925,SHP006926,ORD006926,2022-10-17,2022-10-22,XPRESSBEES,125.67,Delivered,5.0
6947,SHP006948,ORD006948,2024-06-18,2024-06-25,XpressBees,599.36,Returned to Origin,7.0
9037,SHP006948,ORD006948,2024-06-18,2024-06-25,XpressBees,599.36,Returned to Origin,7.0
9038,SHP007535,ORD007535,2024-07-03,2024-07-06,DTDC,529.49,Returned to Origin,3.0
7534,SHP007535,ORD007535,2024-07-03,2024-07-06,DTDC,529.49,Returned to Origin,3.0

In [55]:
shipments = shipments.drop_duplicates()
products = products.drop_duplicates()
suppliers = suppliers.drop_duplicates()
customers = customers.drop_duplicates()

In [56]:
duplicated = (shipments.duplicated().sum(),
              products.duplicated().sum(),
              suppliers.duplicated().sum(),
              customers.duplicated().sum()
             )
print(duplicated)

(np.int64(0), np.int64(0), np.int64(0), np.int64(0))

In [57]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4000 entries, 0 to 3999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       4000 non-null   object
 1   customer_name     3985 non-null   object
 2   email             3883 non-null   object
 3   phone             4000 non-null   int64
 4   city              4000 non-null   object
 5   state             4000 non-null   object
 6   signup_date       3867 non-null   datetime64[ns]
 7   customer_segment  4000 non-null   object
dtypes: datetime64[ns](1), int64(1), object(6)
memory usage: 281.2+ KB

In [58]:
customers["phone"].astype(str).str.len().value_counts()

phone
10    3791
5      209
Name: count, dtype: int64

In [59]:
customers.loc[customers["phone"].astype(str).str.len() == 5, "phone"] = np.nan
customers["phone"].dropna().astype("Int64").astype(str).str.len().value_counts()

phone
10    3791
Name: count, dtype: int64

In [60]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4000 entries, 0 to 3999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       4000 non-null   object
 1   customer_name     3985 non-null   object
 2   email             3883 non-null   object
 3   phone             3791 non-null   float64
 4   city              4000 non-null   object
 5   state             4000 non-null   object
 6   signup_date       3867 non-null   datetime64[ns]
 7   customer_segment  4000 non-null   object
dtypes: datetime64[ns](1), float64(1), object(6)
memory usage: 281.2+ KB

### Finding Irregularities in names

In [61]:
customers["customer_segment"]

0       premium
1       premium
2       Regular
3       regular
4       premium
         ...
3995    Regular
3996        New
3997    regular
3998        VIP
3999        VIP
Name: customer_segment, Length: 4000, dtype: object

In [62]:
def check_categories(df):
    cat_cols = df.select_dtypes(include="object").columns

    for col in cat_cols:
        print(f"{'='*50}")
        print(f"column: {col}")
        print(df[col].value_counts(dropna=False))

        #standardize
        df[col] = df[col].str.strip().str.title()

        print("\_n After:")
        print(df[col].value_counts(dropna=False))

    return df

In [63]:
customers = check_categories(customers)

==================================================
column: customer_id
customer_id
CUST00001    1
CUST02672    1
CUST02659    1
CUST02660    1
CUST02661    1
            ..
CUST01339    1
CUST01340    1
CUST01341    1
CUST01342    1
CUST04000    1
Name: count, Length: 4000, dtype: int64
\_n After:
customer_id
Cust00001    1
Cust02672    1
Cust02659    1
Cust02660    1
Cust02661    1
            ..
Cust01339    1
Cust01340    1
Cust01341    1
Cust01342    1
Cust04000    1
Name: count, Length: 4000, dtype: int64
==================================================
column: customer_name
customer_name
NaN                15
Saanvi Williams    10
Lucas Gupta         9
Pari Reddy          9
Ananya Miller       8
                   ..
ARYAN SINGH         1
ira reddy           1
Liam Singh          1
ira brown           1
lucas brown         1
Name: count, Length: 1628, dtype: int64
\_n After:
customer_name
NaN                15
Aadhya Iyer        12
Charlotte Nair     12
Saanvi Williams    11
Anaya Singh        11
                   ..
Myra Singh          1
Henry Smith         1
Ishaan Wilson       1
Aadhya Sharma       1
Aditya Williams     1
Name: count, Length: 796, dtype: int64
==================================================
column: email
email
NaN                                 117
ananya.miller1@mail.com               1
ishaan.miller2654@yahoo.com           1
aadhya.anderson2656_at_gmail.com      1
aadhya.iyer2657@outlook.com           1
                                   ...
sophia.kumar1333@mail.com             1
michael.brown1334@mail.com            1
myra.garcia1335@yahoo.com             1
alexander.johnson1336@mail.com        1
ananya.kumar4000@outlook.com          1
Name: count, Length: 3884, dtype: int64
\_n After:
email
NaN                                 117
Ananya.Miller1@Mail.Com               1
Ishaan.Miller2654@Yahoo.Com           1
Aadhya.Anderson2656_At_Gmail.Com      1
Aadhya.Iyer2657@Outlook.Com           1
                                   ...
Sophia.Kumar1333@Mail.Com             1
Michael.Brown1334@Mail.Com            1
Myra.Garcia1335@Yahoo.Com             1
Alexander.Johnson1336@Mail.Com        1
Ananya.Kumar4000@Outlook.Com          1
Name: count, Length: 3884, dtype: int64
==================================================
column: city
city
Nashik       155
Ahmedabad    154
Hyderabad    152
Ludhiana     152
Chennai      150
Delhi        149
Jaipur       148
Lucknow      147
Mumbai       147
Indore       146
Agra         144
Bhopal       144
Bengaluru    139
Kanpur       136
Vadodara     134
Pune         131
Surat        131
Nagpur       131
Patna        129
Kolkata      126
INDORE        40
BENGALURU     38
AHMEDABAD     38
ludhiana      36
BHOPAL        36
KOLKATA       35
LUDHIANA      32
MUMBAI        32
indore        32
mumbai        31
VADODARA      31
pune          31
nagpur        31
vadodara      31
LUCKNOW       30
kolkata       30
ahmedabad     29
agra          29
CHENNAI       29
chennai       29
DELHI         29
patna         29
delhi         28
PATNA         28
NASHIK        28
AGRA          27
NAGPUR        27
lucknow       27
hyderabad     27
PUNE          26
kanpur        25
JAIPUR        25
SURAT         25
jaipur        25
bengaluru     24
nashik        23
HYDERABAD     22
surat         22
bhopal        20
KANPUR        18
Name: count, dtype: int64
\_n After:
city
Ahmedabad    221
Ludhiana     220
Indore       218
Mumbai       210
Chennai      208
Nashik       206
Delhi        206
Lucknow      204
Bengaluru    201
Hyderabad    201
Bhopal       200
Agra         200
Jaipur       198
Vadodara     196
Kolkata      191
Nagpur       189
Pune         188
Patna        186
Kanpur       179
Surat        178
Name: count, dtype: int64
==================================================
column: state
state
Maharashtra       793
Gujarat           595
Uttar Pradesh     583
Madhya Pradesh    418
Punjab            220
Tamil Nadu        208
Delhi             206
Karnataka         201
Telangana         201
Rajasthan         198
West Bengal       191
Bihar             186
Name: count, dtype: int64
\_n After:
state
Maharashtra       793
Gujarat           595
Uttar Pradesh     583
Madhya Pradesh    418
Punjab            220
Tamil Nadu        208
Delhi             206
Karnataka         201
Telangana         201
Rajasthan         198
West Bengal       191
Bihar             186
Name: count, dtype: int64
==================================================
column: customer_segment
customer_segment
regular    702
premium    701
Regular    665
New        651
VIP        649
Premium    632
Name: count, dtype: int64
\_n After:
customer_segment
Regular    1367
Premium    1333
New         651
Vip         649
Name: count, dtype: int64

C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()

In [64]:
order_items = check_categories(order_items)

==================================================
column: order_item_id
order_item_id
OI0000001    1
OI0012100    1
OI0012106    1
OI0012105    1
OI0012104    1
            ..
OI0006055    1
OI0006056    1
OI0006057    1
OI0006058    1
OI0018149    1
Name: count, Length: 18109, dtype: int64
\_n After:
order_item_id
Oi0000001    1
Oi0012100    1
Oi0012106    1
Oi0012105    1
Oi0012104    1
            ..
Oi0006055    1
Oi0006056    1
Oi0006057    1
Oi0006058    1
Oi0018149    1
Name: count, Length: 18109, dtype: int64
==================================================
column: order_id
order_id
ORD003673    7
ORD004811    6
ORD004295    6
ORD008941    6
ORD003530    6
            ..
ORD004196    1
ORD004192    1
ORD004190    1
ORD004189    1
ORD004503    1
Name: count, Length: 8987, dtype: int64
\_n After:
order_id
Ord003673    7
Ord004811    6
Ord004295    6
Ord008941    6
Ord003530    6
            ..
Ord004196    1
Ord004192    1
Ord004190    1
Ord004189    1
Ord004503    1
Name: count, Length: 8987, dtype: int64
==================================================
column: product_id
product_id
PROD00132    70
PROD00135    67
PROD00142    66
PROD00552    60
PROD00312    55
             ..
PROD9156      1
PROD9077      1
PROD9777      1
PROD9817      1
PROD9698      1
Name: count, Length: 777, dtype: int64
\_n After:
product_id
Prod00132    70
Prod00135    67
Prod00142    66
Prod00552    60
Prod00312    55
             ..
Prod9156      1
Prod9077      1
Prod9777      1
Prod9817      1
Prod9698      1
Name: count, Length: 777, dtype: int64

C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()

In [65]:
orders = check_categories(orders)

==================================================
column: order_id
order_id
ORD000001    1
ORD005994    1
ORD006008    1
ORD006007    1
ORD006006    1
            ..
ORD003012    1
ORD003011    1
ORD003010    1
ORD003009    1
ORD009000    1
Name: count, Length: 8658, dtype: int64
\_n After:
order_id
Ord000001    1
Ord005994    1
Ord006008    1
Ord006007    1
Ord006006    1
            ..
Ord003012    1
Ord003011    1
Ord003010    1
Ord003009    1
Ord009000    1
Name: count, Length: 8658, dtype: int64
==================================================
column: customer_id
customer_id
CUST01124    8
CUST03466    8
CUST02806    8
CUST01192    8
CUST02296    8
            ..
CUST03948    1
CUST03875    1
CUST01541    1
CUST01753    1
CUST54094    1
Name: count, Length: 3599, dtype: int64
\_n After:
customer_id
Cust01124    8
Cust03466    8
Cust02806    8
Cust01192    8
Cust02296    8
            ..
Cust03948    1
Cust03875    1
Cust01541    1
Cust01753    1
Cust54094    1
Name: count, Length: 3599, dtype: int64
==================================================
column: warehouse_id
warehouse_id
WH016    530
WH009    506
WH015    497
WH007    497
WH017    494
WH005    494
WH011    489
WH018    486
WH003    485
WH014    483
WH008    483
WH013    477
WH004    472
WH012    463
WH006    460
WH001    455
WH002    447
WH010    440
Name: count, dtype: int64
\_n After:
warehouse_id
Wh016    530
Wh009    506
Wh015    497
Wh007    497
Wh017    494
Wh005    494
Wh011    489
Wh018    486
Wh003    485
Wh014    483
Wh008    483
Wh013    477
Wh004    472
Wh012    463
Wh006    460
Wh001    455
Wh002    447
Wh010    440
Name: count, dtype: int64
==================================================
column: order_status
order_status
Shipped       1032
Delivered     1015
Processing    1014
Cancelled     1008
Returned      1004
Pending        993
CANCELLED      245
RETURNED       225
pending        225
SHIPPED        223
PENDING        223
processing     220
DELIVERED      220
shipped        219
PROCESSING     219
delivered      193
cancelled      192
returned       188
Name: count, dtype: int64
\_n After:
order_status
Shipped       1474
Processing    1453
Cancelled     1445
Pending       1441
Delivered     1428
Returned      1417
Name: count, dtype: int64
==================================================
column: payment_mode
payment_mode
Debit Card          1274
Credit Card         1267
Net Banking         1260
cod                 1246
Cash on Delivery    1231
COD                 1218
UPI                 1162
Name: count, dtype: int64
\_n After:
payment_mode
Cod                 2464
Debit Card          1274
Credit Card         1267
Net Banking         1260
Cash On Delivery    1231
Upi                 1162
Name: count, dtype: int64

In [66]:
shipments = check_categories(shipments)

==================================================
column: shipment_id
shipment_id
SHP000002    1
SHP005975    1
SHP005989    1
SHP005988    1
SHP005987    1
            ..
SHP002984    1
SHP002982    1
SHP002981    1
SHP002980    1
SHP009030    1
Name: count, Length: 7429, dtype: int64
\_n After:
shipment_id
Shp000002    1
Shp005975    1
Shp005989    1
Shp005988    1
Shp005987    1
            ..
Shp002984    1
Shp002982    1
Shp002981    1
Shp002980    1
Shp009030    1
Name: count, Length: 7429, dtype: int64
==================================================
column: order_id
order_id
ORD003673    2
ORD007266    2
ORD001158    2
ORD003127    2
ORD000043    2
            ..
ORD002975    1
ORD002974    1
ORD002973    1
ORD002972    1
ORD008941    1
Name: count, Length: 7407, dtype: int64
\_n After:
order_id
Ord003673    2
Ord007266    2
Ord001158    2
Ord003127    2
Ord000043    2
            ..
Ord002975    1
Ord002974    1
Ord002973    1
Ord002972    1
Ord008941    1
Name: count, Length: 7407, dtype: int64
==================================================
column: carrier
carrier
DTDC          902
Delhivery     765
BlueDart      758
FedEx         757
XpressBees    751
IndiaPost     750
Ekart         701
BLUEDART      171
EKART         170
INDIAPOST     169
FEDEX         165
DELHIVERY     162
ekart         161
fedex         154
indiapost     154
delhivery     152
xpressbees    152
dtdc          151
bluedart      145
XPRESSBEES    139
Name: count, dtype: int64
\_n After:
carrier
Delhivery     1079
Fedex         1076
Bluedart      1074
Indiapost     1073
Dtdc          1053
Xpressbees    1042
Ekart         1032
Name: count, dtype: int64
==================================================
column: delivery_status
delivery_status
Returned to Origin    1068
Delivered             1059
Delayed               1052
In Transit            1044
Lost                  1010
IN TRANSIT             257
DELIVERED              255
LOST                   245
RETURNED TO ORIGIN     232
returned to origin     212
lost                   210
delivered              202
DELAYED                200
delayed                194
in transit             189
Name: count, dtype: int64
\_n After:
delivery_status
Delivered             1516
Returned To Origin    1512
In Transit            1490
Lost                  1465
Delayed               1446
Name: count, dtype: int64

C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()

In [67]:
suppliers = check_categories(suppliers)

==================================================
column: supplier_id
supplier_id
SUP0001    1
SUP0002    1
SUP0033    1
SUP0034    1
SUP0035    1
SUP0036    1
SUP0037    1
SUP0038    1
SUP0039    1
SUP0040    1
SUP0041    1
SUP0042    1
SUP0043    1
SUP0044    1
SUP0045    1
SUP0046    1
SUP0047    1
SUP0048    1
SUP0049    1
SUP0050    1
SUP0051    1
SUP0052    1
SUP0053    1
SUP0054    1
SUP0055    1
SUP0056    1
SUP0057    1
SUP0058    1
SUP0059    1
SUP0032    1
SUP0031    1
SUP0030    1
SUP0015    1
SUP0003    1
SUP0004    1
SUP0005    1
SUP0006    1
SUP0007    1
SUP0008    1
SUP0009    1
SUP0010    1
SUP0011    1
SUP0012    1
SUP0013    1
SUP0014    1
SUP0016    1
SUP0029    1
SUP0017    1
SUP0018    1
SUP0019    1
SUP0020    1
SUP0021    1
SUP0022    1
SUP0023    1
SUP0024    1
SUP0025    1
SUP0026    1
SUP0027    1
SUP0028    1
SUP0060    1
Name: count, dtype: int64
\_n After:
supplier_id
Sup0001    1
Sup0002    1
Sup0033    1
Sup0034    1
Sup0035    1
Sup0036    1
Sup0037    1
Sup0038    1
Sup0039    1
Sup0040    1
Sup0041    1
Sup0042    1
Sup0043    1
Sup0044    1
Sup0045    1
Sup0046    1
Sup0047    1
Sup0048    1
Sup0049    1
Sup0050    1
Sup0051    1
Sup0052    1
Sup0053    1
Sup0054    1
Sup0055    1
Sup0056    1
Sup0057    1
Sup0058    1
Sup0059    1
Sup0032    1
Sup0031    1
Sup0030    1
Sup0015    1
Sup0003    1
Sup0004    1
Sup0005    1
Sup0006    1
Sup0007    1
Sup0008    1
Sup0009    1
Sup0010    1
Sup0011    1
Sup0012    1
Sup0013    1
Sup0014    1
Sup0016    1
Sup0029    1
Sup0017    1
Sup0018    1
Sup0019    1
Sup0020    1
Sup0021    1
Sup0022    1
Sup0023    1
Sup0024    1
Sup0025    1
Sup0026    1
Sup0027    1
Sup0028    1
Sup0060    1
Name: count, dtype: int64
==================================================
column: supplier_name
supplier_name
Davis Global            3
Iyer Manufacturing      2
Sharma Traders          2
reddy manufacturing     2
Patel Traders           2
Brown Traders           2
Verma Exports           2
Gupta Traders           1
brown enterprises       1
Johnson Traders         1
JONES GLOBAL            1
WILLIAMS EXPORTS        1
Reddy Traders           1
Davis Exports           1
kumar industries        1
jones industries        1
Rao Global              1
Kumar Enterprises       1
Reddy Enterprises       1
NAIR TRADERS            1
iyer exports            1
Kumar Manufacturing     1
Verma Industries        1
Brown Global            1
Iyer Industries         1
davis manufacturing     1
Nair Traders            1
Iyer Traders            1
Brown Exports           1
Verma Enterprises       1
Patel Manufacturing     1
Nair Exports            1
Johnson Global          1
Williams Traders        1
Williams Industries     1
nair enterprises        1
Jones Manufacturing     1
Wilson Enterprises      1
jones exports           1
Wilson Manufacturing    1
Sharma Enterprises      1
garcia traders          1
Smith Traders           1
nair global             1
Davis Traders           1
RAO EXPORTS             1
miller traders          1
rao manufacturing       1
PATEL INDUSTRIES        1
verma exports           1
Miller Exports          1
ANDERSON GLOBAL         1
Name: count, dtype: int64
\_n After:
supplier_name
Verma Exports           3
Davis Global            3
Brown Traders           2
Iyer Manufacturing      2
Sharma Traders          2
Reddy Manufacturing     2
Patel Traders           2
Nair Traders            2
Jones Global            1
Williams Exports        1
Brown Enterprises       1
Gupta Traders           1
Davis Exports           1
Reddy Traders           1
Rao Global              1
Jones Industries        1
Johnson Traders         1
Kumar Enterprises       1
Kumar Industries        1
Reddy Enterprises       1
Iyer Exports            1
Kumar Manufacturing     1
Verma Industries        1
Brown Global            1
Iyer Industries         1
Davis Manufacturing     1
Iyer Traders            1
Brown Exports           1
Verma Enterprises       1
Garcia Traders          1
Nair Exports            1
Johnson Global          1
Williams Traders        1
Williams Industries     1
Nair Enterprises        1
Jones Manufacturing     1
Wilson Enterprises      1
Jones Exports           1
Wilson Manufacturing    1
Patel Manufacturing     1
Sharma Enterprises      1
Smith Traders           1
Nair Global             1
Davis Traders           1
Rao Exports             1
Miller Traders          1
Rao Manufacturing       1
Patel Industries        1
Miller Exports          1
Anderson Global         1
Name: count, dtype: int64
==================================================
column: country
country
China         13
Bangladesh     9
Vietnam        8
Germany        8
India          7
USA            7
Indonesia      6
Sri Lanka      2
Name: count, dtype: int64
\_n After:
country
China         13
Bangladesh     9
Vietnam        8
Germany        8
India          7
Usa            7
Indonesia      6
Sri Lanka      2
Name: count, dtype: int64

C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()

In [68]:
products = check_categories(products)

==================================================
column: product_id
product_id
PROD00001    1
PROD00412    1
PROD00396    1
PROD00397    1
PROD00398    1
            ..
PROD00203    1
PROD00204    1
PROD00205    1
PROD00206    1
PROD00600    1
Name: count, Length: 586, dtype: int64
\_n After:
product_id
Prod00001    1
Prod00412    1
Prod00396    1
Prod00397    1
Prod00398    1
            ..
Prod00203    1
Prod00204    1
Prod00205    1
Prod00206    1
Prod00600    1
Name: count, Length: 586, dtype: int64
==================================================
column: product_name
product_name
Team Sports Item 1       1
outdoor item 412         1
Cameras Item 396         1
Men Clothing Item 397    1
Team Sports Item 398     1
                        ..
STAPLES ITEM 203         1
Mobiles Item 204         1
Bags Item 205            1
DAIRY ITEM 206           1
MOBILES ITEM 600         1
Name: count, Length: 586, dtype: int64
\_n After:
product_name
Team Sports Item 1       1
Outdoor Item 412         1
Cameras Item 396         1
Men Clothing Item 397    1
Team Sports Item 398     1
                        ..
Staples Item 203         1
Mobiles Item 204         1
Bags Item 205            1
Dairy Item 206           1
Mobiles Item 600         1
Name: count, Length: 586, dtype: int64
==================================================
column: category
category
Grocery           76
Home & Kitchen    74
Sports            70
Electronics       69
Fashion           59
Books             56
BOOKS             21
HOME & KITCHEN    20
FASHION           19
home & kitchen    17
SPORTS            17
electronics       15
sports            13
ELECTRONICS       13
GROCERY           13
grocery           13
books             12
fashion            9
Name: count, dtype: int64
\_n After:
category
Home & Kitchen    111
Grocery           102
Sports            100
Electronics        97
Books              89
Fashion            87
Name: count, dtype: int64
==================================================
column: sub_category
sub_category
Storage           20
Furniture         19
Yoga              19
Cycling           18
Decor             18
                  ..
storage            1
CYCLING            1
YOGA               1
ACADEMIC           1
women clothing     1
Name: count, Length: 87, dtype: int64
\_n After:
sub_category
Decor             28
Yoga              24
Cameras           24
Storage           23
Comics            23
Furniture         22
Mobiles           22
Snacks            22
Children          22
Watches           22
Beverages         22
Cycling           22
Personal Care     21
Dairy             21
Team Sports       20
Appliances        19
Cookware          19
Bags              19
Laptops           19
Non-Fiction       18
Fitness           17
Outdoor           17
Men Clothing      17
Staples           16
Headphones        16
Accessories       16
Academic          15
Women Clothing    15
Footwear          14
Fiction           11
Name: count, dtype: int64
==================================================
column: supplier_id
supplier_id
SUP0042    23
SUP0003    21
SUP0040    19
SUP0052    17
SUP0006    16
SUP0030    14
SUP0038    14
SUP0034    14
SUP0027    13
SUP0020    13
SUP0046    12
SUP0039    12
SUP0008    12
SUP0051    12
SUP0012    12
SUP0004    12
SUP0019    11
SUP0007    11
SUP0026    11
SUP0044    11
SUP0047    11
SUP0045    10
SUP0035    10
SUP0013    10
SUP0041    10
SUP0033     9
SUP0010     9
SUP0025     9
SUP0055     9
SUP0005     9
SUP0056     9
SUP0018     9
SUP0014     9
SUP0028     9
SUP0049     9
SUP0024     8
SUP0017     8
SUP0058     8
SUP0011     8
SUP0032     8
SUP0029     8
SUP0057     8
SUP0016     7
SUP0059     7
SUP0022     7
SUP0031     7
SUP0037     7
SUP0043     7
SUP0002     7
SUP0015     7
SUP0048     7
SUP0036     6
SUP0001     6
SUP0060     6
SUP0021     6
SUP0009     5
SUP0023     5
SUP0053     5
SUP0054     4
SUP0050     3
Name: count, dtype: int64
\_n After:
supplier_id
Sup0042    23
Sup0003    21
Sup0040    19
Sup0052    17
Sup0006    16
Sup0030    14
Sup0038    14
Sup0034    14
Sup0027    13
Sup0020    13
Sup0046    12
Sup0039    12
Sup0008    12
Sup0051    12
Sup0012    12
Sup0004    12
Sup0019    11
Sup0007    11
Sup0026    11
Sup0044    11
Sup0047    11
Sup0045    10
Sup0035    10
Sup0013    10
Sup0041    10
Sup0033     9
Sup0010     9
Sup0025     9
Sup0055     9
Sup0005     9
Sup0056     9
Sup0018     9
Sup0014     9
Sup0028     9
Sup0049     9
Sup0024     8
Sup0017     8
Sup0058     8
Sup0011     8
Sup0032     8
Sup0029     8
Sup0057     8
Sup0016     7
Sup0059     7
Sup0022     7
Sup0031     7
Sup0037     7
Sup0043     7
Sup0002     7
Sup0015     7
Sup0048     7
Sup0036     6
Sup0001     6
Sup0060     6
Sup0021     6
Sup0009     5
Sup0023     5
Sup0053     5
Sup0054     4
Sup0050     3
Name: count, dtype: int64

C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()
C:\Users\RUCHIR\AppData\Local\Temp\ipykernel_20316\944814364.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[col] = df[col].str.strip().str.title()

In [69]:
warehouses = check_categories(warehouses)

==================================================
column: warehouse_id
warehouse_id
WH001    1
WH002    1
WH017    1
WH016    1
WH015    1
WH014    1
WH013    1
WH012    1
WH011    1
WH010    1
WH009    1
WH008    1
WH007    1
WH006    1
WH005    1
WH004    1
WH003    1
WH018    1
Name: count, dtype: int64
\_n After:
warehouse_id
Wh001    1
Wh002    1
Wh017    1
Wh016    1
Wh015    1
Wh014    1
Wh013    1
Wh012    1
Wh011    1
Wh010    1
Wh009    1
Wh008    1
Wh007    1
Wh006    1
Wh005    1
Wh004    1
Wh003    1
Wh018    1
Name: count, dtype: int64
==================================================
column: warehouse_name
warehouse_name
Nagpur Fulfilment Center       1
Indore Fulfilment Center       1
Vadodara Fulfilment Center     1
Bengaluru Fulfilment Center    1
Agra Fulfilment Center         1
Patna Fulfilment Center        1
Mumbai Fulfilment Center       1
Kolkata Fulfilment Center      1
Delhi Fulfilment Center        1
Hyderabad Fulfilment Center    1
Nashik Fulfilment Center       1
Surat Fulfilment Center        1
Ludhiana Fulfilment Center     1
Jaipur Fulfilment Center       1
Ahmedabad Fulfilment Center    1
Kanpur Fulfilment Center       1
Lucknow Fulfilment Center      1
Chennai Fulfilment Center      1
Name: count, dtype: int64
\_n After:
warehouse_name
Nagpur Fulfilment Center       1
Indore Fulfilment Center       1
Vadodara Fulfilment Center     1
Bengaluru Fulfilment Center    1
Agra Fulfilment Center         1
Patna Fulfilment Center        1
Mumbai Fulfilment Center       1
Kolkata Fulfilment Center      1
Delhi Fulfilment Center        1
Hyderabad Fulfilment Center    1
Nashik Fulfilment Center       1
Surat Fulfilment Center        1
Ludhiana Fulfilment Center     1
Jaipur Fulfilment Center       1
Ahmedabad Fulfilment Center    1
Kanpur Fulfilment Center       1
Lucknow Fulfilment Center      1
Chennai Fulfilment Center      1
Name: count, dtype: int64
==================================================
column: city
city
nagpur       1
Indore       1
Vadodara     1
Bengaluru    1
agra         1
patna        1
Mumbai       1
Kolkata      1
Delhi        1
Hyderabad    1
Nashik       1
SURAT        1
Ludhiana     1
Jaipur       1
Ahmedabad    1
Kanpur       1
lucknow      1
Chennai      1
Name: count, dtype: int64
\_n After:
city
Nagpur       1
Indore       1
Vadodara     1
Bengaluru    1
Agra         1
Patna        1
Mumbai       1
Kolkata      1
Delhi        1
Hyderabad    1
Nashik       1
Surat        1
Ludhiana     1
Jaipur       1
Ahmedabad    1
Kanpur       1
Lucknow      1
Chennai      1
Name: count, dtype: int64
==================================================
column: state
state
Maharashtra       3
Uttar Pradesh     3
Gujarat           3
Madhya Pradesh    1
Rajasthan         1
Punjab            1
Telangana         1
Delhi             1
West Bengal       1
Bihar             1
Karnataka         1
Tamil Nadu        1
Name: count, dtype: int64
\_n After:
state
Maharashtra       3
Uttar Pradesh     3
Gujarat           3
Madhya Pradesh    1
Rajasthan         1
Punjab            1
Telangana         1
Delhi             1
West Bengal       1
Bihar             1
Karnataka         1
Tamil Nadu        1
Name: count, dtype: int64

In [70]:
order_items.head()

  order_item_id   order_id product_id  quantity  discount_pct
0     Oi0000001  Ord000001  Prod00419       5.0             0
1     Oi0000002  Ord000002  Prod00090      10.0             0
2     Oi0000003  Ord000002  Prod00503      10.0             0
3     Oi0000004  Ord000002  Prod00018       5.0             0
4     Oi0000005  Ord000002  Prod00591       5.0            20

In [71]:
len(order_items)

18109

In [72]:
order_items[order_items["quantity"]<0]

      order_item_id   order_id product_id  quantity  discount_pct
6         Oi0000007  Ord000004  Prod00563      -1.0            15
7         Oi0000008  Ord000004  Prod00442      -1.0             5
15        Oi0000016  Ord000009  Prod00367      -1.0            25
18        Oi0000019  Ord000010  Prod00250      -1.0            15
41        Oi0000042  Ord000021  Prod00576      -1.0             0
...             ...        ...        ...       ...           ...
18111     Oi0018112  Ord004270  Prod00131      -1.0            20
18113     Oi0018114  Ord005785  Prod00477      -1.0            20
18114     Oi0018115  Ord001158  Prod00571      -1.0             5
18135     Oi0018136  Ord005873   Prod9698      -1.0            25
18136     Oi0018137  Ord005873  Prod00100      -1.0            25

[1849 rows x 5 columns]

In [73]:
order_items = order_items[order_items["quantity"]>=0]

In [74]:
order_items[order_items["quantity"]<0]

Empty DataFrame
Columns: [order_item_id, order_id, product_id, quantity, discount_pct]
Index: []

In [75]:
len(order_items)

16260

In [76]:
invalid_customers = orders[~orders["customer_id"].isin(customers["customer_id"])]
print(invalid_customers)
print("total invalid customer_ids:", len(invalid_customers))

       order_id customer_id order_date warehouse_id order_status  \
294   Ord000295   Cust54794 2022-06-14        Wh009     Returned
295   Ord000296   Cust50100 2022-12-08        Wh002    Delivered
320   Ord000321   Cust57269 2023-04-23        Wh013      Shipped
586   Ord000587   Cust57433 2024-05-30        Wh001   Processing
633   Ord000634   Cust52240 2023-01-16        Wh004      Shipped
...         ...         ...        ...          ...          ...
8401  Ord008402   Cust56505 2022-06-16        Wh015      Pending
8524  Ord008525   Cust57594 2024-10-30        Wh014     Returned
8754  Ord008755   Cust52818 2023-01-18        Wh008   Processing
8978  Ord008979   Cust52949 2024-02-16        Wh018      Pending
8980  Ord008981   Cust54094 2024-09-14        Wh002    Delivered

          payment_mode
294        Net Banking
295   Cash On Delivery
320        Net Banking
586   Cash On Delivery
633         Debit Card
...                ...
8401       Net Banking
8524       Credit Card
8754        Debit Card
8978  Cash On Delivery
8980       Net Banking

[79 rows x 6 columns]
total invalid customer_ids: 79

In [77]:
orders = orders[orders["customer_id"].isin(customers["customer_id"])]

In [78]:
orders[~orders["customer_id"].isin(customers["customer_id"])]

Empty DataFrame
Columns: [order_id, customer_id, order_date, warehouse_id, order_status, payment_mode]
Index: []

In [82]:
invalid_products = order_items[~order_items["product_id"].isin(products["product_id"])]
print(invalid_products)
print("total invalid products_ids:", len(invalid_products))

      order_item_id   order_id product_id  quantity  discount_pct
13        Oi0000014  Ord000008   Prod9334       2.0             0
16        Oi0000017  Ord000009  Prod00052       2.0            15
89        Oi0000090  Ord000043  Prod00287       2.0             0
100       Oi0000101  Ord000047  Prod00052       1.0             0
144       Oi0000145  Ord000070  Prod00470       4.0            20
...             ...        ...        ...       ...           ...
18063     Oi0018064  Ord008989  Prod00121       1.0             0
18092     Oi0018093  Ord006189  Prod00052      10.0            15
18099     Oi0018100  Ord004086  Prod00022       2.0             0
18105     Oi0018106  Ord007343  Prod00377      10.0             0
18122     Oi0018123  Ord004295  Prod00287       1.0            25

[567 rows x 5 columns]
total invalid products_ids: 567

In [79]:
print("products:", len(products))
print("order_items:", len(order_items))

products: 586
order_items: 16260

In [88]:
order_items = order_items[
    order_items["product_id"].isin(products["product_id"])
]

In [90]:
order_items[order_items["product_id"].isin(products["product_id"])]

      order_item_id   order_id product_id  quantity  discount_pct
0         Oi0000001  Ord000001  Prod00419       5.0             0
1         Oi0000002  Ord000002  Prod00090      10.0             0
2         Oi0000003  Ord000002  Prod00503      10.0             0
3         Oi0000004  Ord000002  Prod00018       5.0             0
4         Oi0000005  Ord000002  Prod00591       5.0            20
...             ...        ...        ...       ...           ...
18144     Oi0018145  Ord007123  Prod00532       2.0             0
18145     Oi0018146  Ord007123  Prod00338       1.0             0
18146     Oi0018147  Ord000043  Prod00594       1.0             0
18147     Oi0018148  Ord008941  Prod00037       1.0             0
18148     Oi0018149  Ord008941  Prod00396       1.0            10

[15693 rows x 5 columns]

In [91]:
from pathlib import Path

output_folder = Path(r"C:\Users\RUCHIR\anaconda_projects\New_project\data_cleaned")
output_folder.mkdir(exist_ok=True)

customers.to_csv(output_folder / "customers_cleaned.csv", index=False)
orders.to_csv(output_folder / "orders_cleaned.csv", index=False)
order_items.to_csv(output_folder / "order_items_cleaned.csv", index=False)
products.to_csv(output_folder / "products_cleaned.csv", index=False)
shipments.to_csv(output_folder / "shipments_cleaned.csv", index=False)
warehouses.to_csv(output_folder / "warehouses_cleaned.csv", index=False)
suppliers.to_csv(output_folder / "suppliers_cleaned.csv", index=False)

In [92]:
import pandas as pd
import os
from sqlalchemy import create_engine
username = "postgres"
password = "history123"
host = "localhost"
port = "5432"
database = "urban_cart_db"
connection_string = f'postgresql://{username}:{password}@{host}:{port}/{database}'
engine = create_engine(connection_string)
with engine.connect() as con:
    print("connected!!")

connected!!

In [93]:
def load_to_db(file_path, table_name, engine):
    try:
        df = pd.read_csv(file_path, parse_dates=True)
        df.to_sql(name=table_name, con=engine, if_exists="append", index=False)
        print(f"{table_name} loaded: {len(df)} rows")
    except Exception as e:
        print(f"{table_name}: ERROR - {e}")

In [94]:
load_to_db(r"C:\Users\RUCHIR\anaconda_projects\New_project\data_cleaned\customers_cleaned.csv", "customers", engine)
load_to_db(r"C:\Users\RUCHIR\anaconda_projects\New_project\data_cleaned\order_items_cleaned.csv", "order_items", engine)
load_to_db(r"C:\Users\RUCHIR\anaconda_projects\New_project\data_cleaned\orders_cleaned.csv", "orders", engine)
load_to_db(r"C:\Users\RUCHIR\anaconda_projects\New_project\data_cleaned\products_cleaned.csv", "products", engine)
load_to_db(r"C:\Users\RUCHIR\anaconda_projects\New_project\data_cleaned\shipments_cleaned.csv", "shipments", engine)
load_to_db(r"C:\Users\RUCHIR\anaconda_projects\New_project\data_cleaned\suppliers_cleaned.csv", "suppliers", engine)
load_to_db(r"C:\Users\RUCHIR\anaconda_projects\New_project\data_cleaned\warehouses_cleaned.csv", "warehouses", engine)

customers loaded: 4000 rows
order_items loaded: 15693 rows
orders loaded: 8579 rows
products loaded: 586 rows
shipments loaded: 7429 rows
suppliers loaded: 60 rows
warehouses loaded: 18 rows